export const nodes = {
  start: {
    title: 'Start',
    icon: 'lightning-bolt',
    input: 0,
    output: 1,
    allowedInput: ['chat'],
    maxConnection: 1,
    colorGradient: 'from-yellow-400 to-orange-500',
    textColor: 'text-yellow-500',
  },
  chat: {
    title: 'Chats',
    icon: 'chat-alt2',
    input: 1,
    output: 1,
    allowedInput: ['option', 'end', 'annotation'],
    maxConnection: 3,
    colorGradient: 'from-green-400 to-cyan-500',
    textColor: 'text-primary',
    data: {
      chats: [],
    },
  },
  // transition: {
  //   title: 'Transition',
  //   icon: 'location-marker',
  //   input: 1,
  //   output: 1,
  //   allowedInput: [],
  //   colorGradient: 'from-light-blue-400 to-indigo-500',
  //   textColor: 'text-cyan-500',
  //   maxConnection: 1,
  //   data: {
  //     text: '',
  //   },
  // },
  annotation: {
    title: 'Annotation',
    icon: 'annotation',
    input: 1,
    output: 1,
    allowedInput: ['chat', 'option'],
    colorGradient: 'from-light-blue-400 to-indigo-500',
    textColor: 'text-cyan-500',
    maxConnection: 1,
    data: {
      text: '',
    },
  },
  option: {
    title: 'Option',
    icon: 'clipboard-list',
    input: 1,
    output: 1,
    allowedInput: ['chat', 'annotation'],
    colorGradient: 'from-light-blue-400 to-indigo-500',
    textColor: 'text-green-500',
    maxConnection: 1,
    data: {
      text: '',
    },
  },
  end: {
    title: 'Ending',
    icon: 'flag',
    input: 1,
    output: 0,
    allowedInput: [],
    maxConnection: 0,
    colorGradient: 'from-purple-500 to-indigo-500',
    textColor: 'text-purple-500',
  },
};
